name: robuzzle
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # ui dependencies
  drag_and_drop_lists: ^0.4.1
  flutter_slidable: ^3.1.1

  # Storage dependencies
  shared_preferences: ^2.2.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # state management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.6.1

  # dependencies injection
  get_it: ^7.7.0

  # icons
  material_symbols_icons: ^4.2785.1
  gif: ^2.3.0

  # navigation
  go_router: ^14.2.8

  # text
  bordered_text: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Storage dependencies
  ##hive_generator: does not support web
  hive_generator: ^2.0.1
  ##build_runner: does not support web
  build_runner: ^2.4.11
  ##path_provider: does not support web
  path_provider: ^2.1.4

  # test dependencies
  mocktail: ^1.0.4
  ##hive_test: does not support web
  hive_test: ^1.0.1

  # state dependencies
  bloc_test: ^9.0.0
  ##riverpod_generator: does not support web
  riverpod_generator: ^2.4.3
  ##riverpod_lint: does not support web
  riverpod_lint: ^2.3.13




flutter:
  assets:
    - assets/dataPuzzles/
    - assets/gif/

  uses-material-design: true
